#!/bin/sh

set -eu

VCGEN=/opt/vc/bin/vcgencmd
TEXTFILE=/var/lib/node_exporter/textfile_collector/raspberry-metrics.prom
TEMPFILE=$TEXTFILE.$$

mkdir -p /var/lib/node_exporter/textfile_collector/

cat /dev/null > $TEMPFILE

for sensor in `ls /sys/class/thermal/`;
do
	TEMP=$(awk '{printf "%.2f", $1/1000}' /sys/class/thermal/$sensor/temp)
	CHIP=$(cat /sys/class/thermal/$sensor/type)

	if [ -z "$TEMP" ];
	then
		echo "ERROR: Temperature variable empty for $sensor" >&2
	else
		echo "rpi_temperature{chip=\"$CHIP\",sensor=\"$sensor\"} ${TEMP}" >> $TEMPFILE
	fi
done

for id in arm core h264 isp v3d uart pwm emmc pixel vec hdmi dpi; do
	echo "rpi_freq{device=\"$id\"} $($VCGEN measure_clock $id | awk '{split($0,a,"="); print a[2]}')" >> $TEMPFILE
done

for id in core sdram_c sdram_i sdram_p; do
	echo "rpi_volt{device=\"$id\"} $($VCGEN measure_volts $id | awk '{split($0,a,"="); print a[2]}' | sed 's/V$//')" >> $TEMPFILE
done

for id in arm gpu; do
	echo "rpi_mem{device=\"$id\"} $($VCGEN get_mem $id | awk '{split($0,a,"="); print a[2]}' | sed 's/M$//')" >> $TEMPFILE
done
mv $TEMPFILE $TEXTFILE
